language: node_js
node_js:
  - '8'
before_script:
  - npm install -g ajv-cli
script:
  - ajv compile -s callmetadata.schema.json
  - ./tools/formatter.js callmetadata.schema.json | diff callmetadata.schema.json - > /dev/null
